blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Community forum
    url: https://community.jenkins.io/
    about: Please ask and answer questions here
  - name: âœ‰ï¸ Mailing lists
    url: https://www.jenkins.io/mailing-lists/
    about: You can also raise a question on the infra mailing list
