name: Notify users based on issue labels
on:
  issues:
    types: [labeled]
jobs:
  autonotifier:
    runs-on: ubuntu-latest
    steps:
      - uses: jenschelkopf/issue-label-notification-action@1.3
        with:
          recipients: |
            crowdin=@crowdin-admins
            helpdesk=@lemeurherve
            test=@test-team
